title: "Cybher Girls"
author: "NaZiya Whitlock"
description: "Written by NaZiya Whitlock"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {url: "ziya.pdf", title: "CV"}
  - {title: "Blog", file: "blog.md"}
  - {title: "About Author", file: "author.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Email, url: "mailto:whitlocknm@gmail.com"}
  - {title: Github, url: "https://github.com/cybhergirls"}
  - {title: YouTube, url: "https://www.youtube.com/@cybhergirls"}
  - {title: TikTok, url: "https://www.tiktok.com/@cybhergirls?_t=8XFavj3j3ud&_r=1"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
